### ISSUE TITLE
Icon

### ISSUE THREAD

**Issue by fehmi** [jashephe/Gmail-Notifier#19]
I think you have to simplify notification icon. Also menubar icon may change to red if there is a new mail just like not login icon. And one more suggestion, it would be awesome if we can select single mail and open it instead of open whole inbox every time.

**Comment by ux531** [comment]
Hi James, i have a question about the menubar icon. I replaced mine for new email with a red color icon so it's more prominent, but it doesn't show as red icon in the bar. I am on version 2.1.0. also the sound for new email does not trigger and i've checked the notification settings.

I have made some icons for you to elaborate and give feedback for all the states you've mentioned in your reply above.

[Gmail Notifier.pdf](https://github.com/jashephe/Gmail-Notifier/files/2052612/Gmail.Notifier.pdf)

If those can be changed by replacing icon files in the when viewing "Package Contents" as i actually did in my case, then why is the icon i use (the red one) no appearing as red.

Thanks for the great app James. I hope you have some time to reply.
