### ISSUE TITLE
Doesn't work for now

### ISSUE THREAD

**Issue by Vizakenjack** [jashephe/Gmail-Notifier#25]
It just shows "no mail" and when I have tried to log out and then log in i got this:

     401. That’s an error.

     Error: deleted_client

     The OAuth client was deleted.

**Comment by jashephe** [comment]
Hi @Vizakenjack, what version are you running?  If you are running v2.1.0, try logging out and logging back in.  It still works for me.

I didn't mean to revoke the older OAuth2 credentials, but I was working in the Google Developer Console and cleared out an old set while I was working on the new multi-account OAuth2 code for v3.  That being said, v2.1.0 runs on newer credentials, so it should be okay; you just might have to log out and back in.

**Comment by Vizakenjack** [comment]
Thanks, I got 2.0.1 version. It works fine now :)

**Comment by jashephe** [comment]
Glad to hear it!
